# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGreeterUser < Formula
  desc "A simple CLI to greet users"
  homepage "https://github.com/abelpenton/go-greeter-user"
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.1/go-greeter-user_1.1.1_darwin_amd64.tar.gz"
      sha256 "9dda424299bcf2685250102f6d6548e475ee15e77ce452905f6b4e44e0e90b05"

      def install
        bin.install "go-greeter-user"
      end
    end
    on_arm do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.1/go-greeter-user_1.1.1_darwin_arm64.tar.gz"
      sha256 "ebb71715feac9cab96cf232b8204e0900fbd5b817d773b66f6899b450bdd3132"

      def install
        bin.install "go-greeter-user"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.1/go-greeter-user_1.1.1_linux_amd64.tar.gz"
        sha256 "b163c0b4ac7a9274fdc02bc4c62b680faa87d2fd9a7815b8eae16da200c3d69a"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.1/go-greeter-user_1.1.1_linux_arm64.tar.gz"
        sha256 "d0d53d057e9590159d38de73045eaad4a3c365cf2fdccce62292e8418d3fb380"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
  end
end
