# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GreeterCli < Formula
  desc "A simple CLI to greet users"
  homepage "https://github.com/abelpenton/go-greeter-user"
  version "1.1.2"

  on_macos do
    on_intel do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.2/go-greeter-user_1.1.2_darwin_amd64.tar.gz"
      sha256 "821742a1a05a7fb427885508720a965ef3f457a3736bc8435fbfd905eadb9180"

      def install
        bin.install "go-greeter-user"
      end
    end
    on_arm do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.2/go-greeter-user_1.1.2_darwin_arm64.tar.gz"
      sha256 "b50576485266f4cb13f3c0e89238ff392bb2aa946af8d38a754211e78afdc89a"

      def install
        bin.install "go-greeter-user"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.2/go-greeter-user_1.1.2_linux_amd64.tar.gz"
        sha256 "127b0bf8b4707d830170c892aa85398e2eec047d523ac3890dea98c60ee7ba0a"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v1.1.2/go-greeter-user_1.1.2_linux_arm64.tar.gz"
        sha256 "7894a8be714a98792890467ebe2fbab77b048ccdab7be13824d397cd5592a9d8"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
  end
end
