# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GreeterCli < Formula
  desc "A simple CLI to greet users"
  homepage "https://github.com/abelpenton/go-greeter-user"
  version "7.0.1"

  on_macos do
    on_intel do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.1/go-greeter-user_Darwin_x86_64.tar.gz"
      sha256 "f35352fd480aa01bcc2498197129fc5fb339509b81500a5d4344f25e9edc611d"

      def install
        bin.install "go-greeter-user"
      end
    end
    on_arm do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.1/go-greeter-user_Darwin_arm64.tar.gz"
      sha256 "5301b077e211e5bfa964c5bec58fe668d18dd39bec1e324d1d8c9252da0a00ac"

      def install
        bin.install "go-greeter-user"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.1/go-greeter-user_Linux_x86_64.tar.gz"
        sha256 "acdacec6e07386355e44d854720c07bc3c5e53c37f43f8b465d674318074ded0"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.1/go-greeter-user_Linux_arm64.tar.gz"
        sha256 "8277c6e10ba30f453d994f6740b647a2dabc219369a05bb64f644c1a5b812ce0"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
  end
end
