# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GreeterCli < Formula
  desc "A simple CLI to greet users"
  homepage "https://github.com/abelpenton/go-greeter-user"
  version "7.0.0"

  on_macos do
    on_intel do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.0/go-greeter-user_Darwin_x86_64.tar.gz"
      sha256 "2db7988413bdfa485b97fb7f5051cc0b45dfa3a9cc3407aabded1c4426963af1"

      def install
        bin.install "go-greeter-user"
      end
    end
    on_arm do
      url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.0/go-greeter-user_Darwin_arm64.tar.gz"
      sha256 "07887e694d4e3d3423410e3598f3b1926aeabbee57cbba6cd2207a54a88a0bcb"

      def install
        bin.install "go-greeter-user"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.0/go-greeter-user_Linux_x86_64.tar.gz"
        sha256 "5090527b09d2c9f9661484028b0a79ade8465c81c8825d6fc244dcdaba5f478c"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abelpenton/go-greeter-user/releases/download/v7.0.0/go-greeter-user_Linux_arm64.tar.gz"
        sha256 "026db827e26ea2a74dd0ee006fb01803a9267b93d17522fa8d2dbcfd8271a241"

        def install
          bin.install "go-greeter-user"
        end
      end
    end
  end
end
